version: '3.4'
services:
  mongo-configserver-a:
    hostname: 'mongo-configserver-a'
    container_name: mongo-configserver-a
    image: mongo:6.0.11
    restart: on-failure
    networks:
        - netApplication
    command: mongod --auth --port 27017 --configsvr --replSet mongo-configserver --dbpath /data/db --keyFile /mongodb.key
    expose: 
        - 27017
    ports: 
        - 10001:27017 
    volumes:
        - ./mongodb.key:/mongodb.key
        - ./mongo-configserver.init.js:/mongo-configserver.init.js
        - ./data/mongo-configserver-a:/data/db
  mongo-configserver-b:
    hostname: 'mongo-configserver-b' 
    container_name: mongo-configserver-b
    image: mongo:6.0.11
    restart: on-failure
    networks:
        - netApplication
    command: mongod --auth --port 27017 --configsvr --replSet mongo-configserver --dbpath /data/db --keyFile /mongodb.key
    expose: 
        - 27017
    ports: 
        - 10002:27017
    volumes:
        - ./mongodb.key:/mongodb.key
        - ./mongo-configserver.init.js:/mongo-configserver.init.js
        - ./data/mongo-configserver-b:/data/db
  mongo-configserver-c:
    hostname: 'mongo-configserver-c'
    container_name: mongo-configserver-c
    image: mongo:6.0.11
    restart: on-failure
    networks:
        - netApplication
    command: mongod --auth --port 27017 --configsvr --replSet mongo-configserver --dbpath /data/db --keyFile /mongodb.key
    expose: 
        - 27017
    ports: 
        - 10003:27017
    volumes:
        - ./mongodb.key:/mongodb.key
        - ./mongo-configserver.init.js:/mongo-configserver.init.js
        - ./data/mongo-configserver-c:/data/db
  mongo-shard-01a:
    hostname: 'mongo-shard-01a'
    container_name: mongo-shard-01a
    image: mongo:6.0.11
    restart: on-failure
    networks:
        - netApplication
    command: mongod --auth --port 27017 --shardsvr --replSet mongo-shard-01 --dbpath /data/db  --keyFile /mongodb.key
    expose: 
        - 27017
    ports: 
        - 20001:27017
    volumes:
        - ./mongodb.key:/mongodb.key
        - ./mongo-shard-01.init.js:/mongo-shard-01.init.js
        - ./data/mongo-shard-01a:/data/db
  mongo-shard-01b:
    hostname: 'mongo-shard-01b'
    container_name: mongo-shard-01b
    image: mongo:6.0.11
    restart: on-failure
    networks:
        - netApplication
    command: mongod --auth --port 27017 --shardsvr --replSet mongo-shard-01 --dbpath /data/db  --keyFile /mongodb.key
    expose: 
        - 27017
    ports: 
        - 20002:27017
    volumes:
        - ./mongodb.key:/mongodb.key
        - ./mongo-shard-01.init.js:/mongo-shard-01.init.js
        - ./data/mongo-shard-01b:/data/db
  mongo-shard-01c:
    hostname: 'mongo-shard-01c'
    container_name: mongo-shard-01c
    image: mongo:6.0.11
    restart: on-failure
    networks:
        - netApplication
    command: mongod --auth --port 27017 --shardsvr --replSet mongo-shard-01 --dbpath /data/db  --keyFile /mongodb.key
    expose: 
        - 27017
    ports: 
        - 20003:27017
    volumes:
        - ./mongodb.key:/mongodb.key
        - ./mongo-shard-01.init.js:/mongo-shard-01.init.js
        - ./data/mongo-shard-01c:/data/db
  mongo-router-01:
    hostname: 'mongo-router-01'
    container_name: mongo-router-01
    image: mongo:6.0.11
    restart: on-failure
    networks:
        - netApplication
    command: mongos --bind_ip 0.0.0.0 --port 27017 --configdb mongo-configserver/mongo-configserver-a:27017,mongo-configserver-b:27017,mongo-configserver-c:27017 --keyFile /mongodb.key
    expose: 
        - 27017
    ports: 
        - 30000:27017
    volumes:
        - ./mongodb.key:/mongodb.key
        - ./mongo-sharding.init.js:/mongo-sharding.init.js
        - ./mongo-auth.init.js:/mongo-auth.init.js
        - ./data/mongo-router-01:/data/db
    depends_on:
      - mongo-configserver-a
      - mongo-configserver-b
      - mongo-configserver-c
      - mongo-shard-01a
      - mongo-shard-01b
      - mongo-shard-01c

networks: 
    netApplication: